export 'colors.res.dart';
export 'durations.res.dart';
export 'icons.res.dart';
export 'images.res.dart';
export 'radius.res.dart';
export 'strings.res.dart';
export 'styles.res.dart';
export 'typograhy.res.dart';
export 'weights.res.dart';
